### PR TITLE
Added many drawing methods

### PR DESCRIPTION
**Pull request by j-waechter**
Hello,

are you willing to merge this bigger code base into your project? I extended it with many drawing methods because I needed it for creating bitmaps that are displayed on the monochrome LCD of the Logitech G13 keyboard.

I think you should rename the module, then, because it supports more than just monochrome images. I already increased the version number.

Here is a list of the features I added:
- Reading 8-bit .bmp files
- Change the color of every pixel in a specific color
- Drawing circles/ellipses
- Inverting the bitmap
- Drawing a bitmap or a portion of it on a bitmap
- Drawing text with a bitmap font (as for now, dependent on [another pull request](https://github.com/mattdesl/bmfont2json/pull/1) of mine to the [`bmfont2json` project](https://github.com/mattdesl/bmfont2json))

Greetings

### CODE REVIEW

**Comment by vonderheide** [comment]
Thanks a lot for your PR, sorry for taking so long to answer. 
I will take a closer look this weekend.

You are right regarding the naming, I must have confused monochrome and greyscale...

**Comment by j-waechter** [comment]
> Thanks a lot for your PR, sorry for taking so long to answer.
> I will take a closer look this weekend.

Please keep in mind that some of the code of the other-repository pull request might be better included in the Font class of this library. It addresses restructuring of the data read from JSON files.

> You are right regarding the naming, I must have confused monochrome and greyscale...

It even is not limited to greyscale. The library supports 32 bits per pixel. Therefore I just called the main class `Bitmap`. I think, if a user uses this library, the user doesn't use another library regarding this subject. So, such a basic name should be okay.

---

Just out of curiosity: How do _you_ display or use the image? Because the file-writing example you provided didn't even write a .bmp header or similar.

**Comment by vonderheide** [comment]
I finally reviewed your PR. Thanks again!

The only thing I notices is that the unit tests now fail. Strangely enough, travis does not fail.

```
> jasmine-node spec

Exception loading: C:\Users\jvonderheide\Documents\mono-bitmap-2\spec\basic-spec.js
[SyntaxError: C:\Users\jvonderheide\Documents\mono-bitmap-2\index.js:7
const assert = require("assert");
^^^^^
Use of const in strict mode.]
```

Also, would you mind updating the unit tests to the changed interface? And perhaps adding unit tests for the new drawing functions?

Answering your questions: I am using the image as part of a DICOM file (medical imaging format).

**Comment by j-waechter** [comment]
> the unit tests now fail. Strangely enough, travis does not fail.

This should be due to the fact that `const` is one of the newer language constructs of JavaScript. I'm running Node.js 5.4.1. Travis probably runs some newer version, too. The last commit to https://github.com/mhevery/jasmine-node was on 16 Jul 2014, so it could be outdated. See [here](http://stackoverflow.com/a/23151062/5789167) for a possible solution for older versions of Node.js.

> would you mind updating the unit tests to the changed interface? And perhaps adding unit tests for the new drawing functions?

Unfortunately, I'm new to these testing frameworks and have no idea how and why I should test some outcome of drawing methods. These tests already written there seem strange to me at first glance.

What seems like a good idea to me is being able to write .bmp files and run a custom test in using this without a testing framework.

---

Another important question: As it seems you never use color with the images. But it is uncommon to have a greyscale image format with more than 256 shades (1 byte per pixel). So, is it really necessary for you to have a library that isn't fixed to the viewpoint of RGB values? Otherwise, I would perhaps incorporate some 5-bits-6-bits-5-bits logic for 16-bits images (RGB).

**Comment by j-waechter** [comment]
Too late for a reply. I implemented RGB logic.  :wink: Greyscale logic is available with 256 shades and a palette, or by not using the RGB-related methods.

I provided a test script that saves a `.bmp` file. The methods called are connected with other methods so the very majority of the functions is basically tested thereby.

See the commit messages for more information.

The switch `--image-file-extension` is available when this pull request from the `bmfont2json` tool is merged: https://github.com/mattdesl/bmfont2json/pull/2.

**Comment by vonderheide** [comment]
Sorry again for the late reply.

I just merged most of your PR. Wherever possible, I reverted some of your interface changes back to the old signatures (drawRectangle => drawFilledRect, drawGradientRectangle => drawGradientRect).
Although your interface changes were perfectly fine, I wanted to limit the amount of work that users of this package (i.e. me ;) ) have to do when upgrading.

BTW: I do need support for greyscale images with up to four 4 bytes per pixel. But since I don't use the BMP-specific functionality, that is still working as before.

**Comment by j-waechter** [comment]
Thanks for merging.

I just have to admit that `drawFilledRect()` can also draw an unfilled rectangle with just a border.

**Comment by j-waechter** [comment]
Thanks for merging.
- I just have to admit that `drawFilledRect()` can also draw an unfilled rectangle with just a border.
- Also note that the old `drawGradientRect()` method creates a slightly more uneven gradient; there's a jump to the lightest color (see light gradient pixels in attached images; view it zoomed without blurring)
- The npm and GitHub module names should also be renamed

Old gradient method:
old_gradient_method

Proposed gradient method:
proposed_gradient_method

**Pull request merged**
